INSERT INTO oscar (titolo, anno, categoria, vincitore) VALUES

-- 2016
('La La Land', 2016, 'Best Picture Candidate', NULL),
('Moonlight', 2016, 'Best Picture Candidate', NULL),
('Arrival', 2016, 'Best Picture Candidate', NULL),
('Hacksaw Ridge', 2016, 'Best Picture Candidate', NULL),
('Manchester by the Sea', 2016, 'Best Picture Candidate', NULL),
('Fences', 2016, 'Best Picture Candidate', NULL),
('Hell or High Water', 2016, 'Best Picture Candidate', NULL),
('Lion', 2016, 'Best Picture Candidate', NULL),
('Hidden Figures', 2016, 'Best Picture Candidate', NULL),
('Silence', 2016, 'Best Picture Candidate', NULL),

-- 2017
('The Shape of Water', 2017, 'Best Picture Candidate', NULL),
('Dunkirk', 2017, 'Best Picture Candidate', NULL),
('Get Out', 2017, 'Best Picture Candidate', NULL),
('Three Billboards Outside Ebbing, Missouri', 2017, 'Best Picture Candidate', NULL),
('Lady Bird', 2017, 'Best Picture Candidate', NULL),
('Phantom Thread', 2017, 'Best Picture Candidate', NULL),
('Call Me by Your Name', 2017, 'Best Picture Candidate', NULL),
('Darkest Hour', 2017, 'Best Picture Candidate', NULL),
('The Post', 2017, 'Best Picture Candidate', NULL),
('Blade Runner 2049', 2017, 'Best Picture Candidate', NULL),

-- 2018
('Green Book', 2018, 'Best Picture Candidate', NULL),
('Roma', 2018, 'Best Picture Candidate', NULL),
('Black Panther', 2018, 'Best Picture Candidate', NULL),
('Bohemian Rhapsody', 2018, 'Best Picture Candidate', NULL),
('A Star Is Born', 2018, 'Best Picture Candidate', NULL),
('Vice', 2018, 'Best Picture Candidate', NULL),
('The Favourite', 2018, 'Best Picture Candidate', NULL),
('BlacKkKlansman', 2018, 'Best Picture Candidate', NULL),
('First Man', 2018, 'Best Picture Candidate', NULL),
('If Beale Street Could Talk', 2018, 'Best Picture Candidate', NULL),

-- 2019
('Parasite', 2019, 'Best Picture Candidate', NULL),
('1917', 2019, 'Best Picture Candidate', NULL),
('Joker', 2019, 'Best Picture Candidate', NULL),
('Once Upon a Time in Hollywood', 2019, 'Best Picture Candidate', NULL),
('The Irishman', 2019, 'Best Picture Candidate', NULL),
('Ford v Ferrari', 2019, 'Best Picture Candidate', NULL),
('Marriage Story', 2019, 'Best Picture Candidate', NULL),
('Little Women', 2019, 'Best Picture Candidate', NULL),
('Jojo Rabbit', 2019, 'Best Picture Candidate', NULL),
('Knives Out', 2019, 'Best Picture Candidate', NULL),

-- 2020
('Nomadland', 2020, 'Best Picture Candidate', NULL),
('The Trial of the Chicago 7', 2020, 'Best Picture Candidate', NULL),
('Minari', 2020, 'Best Picture Candidate', NULL),
('Sound of Metal', 2020, 'Best Picture Candidate', NULL),
('Promising Young Woman', 2020, 'Best Picture Candidate', NULL),
('The Father', 2020, 'Best Picture Candidate', NULL),
('Mank', 2020, 'Best Picture Candidate', NULL),
('Judas and the Black Messiah', 2020, 'Best Picture Candidate', NULL),
('Tenet', 2020, 'Best Picture Candidate', NULL),
('Soul', 2020, 'Best Picture Candidate', NULL),

-- 2021
('CODA', 2021, 'Best Picture Candidate', NULL),
('Dune', 2021, 'Best Picture Candidate', NULL),
('Belfast', 2021, 'Best Picture Candidate', NULL),
('The Power of the Dog', 2021, 'Best Picture Candidate', NULL),
('West Side Story', 2021, 'Best Picture Candidate', NULL),
('Drive My Car', 2021, 'Best Picture Candidate', NULL),
('King Richard', 2021, 'Best Picture Candidate', NULL),
('Licorice Pizza', 2021, 'Best Picture Candidate', NULL),
('Don’t Look Up', 2021, 'Best Picture Candidate', NULL),
('Nightmare Alley', 2021, 'Best Picture Candidate', NULL),

-- 2022
('Everything Everywhere All at Once', 2022, 'Best Picture Candidate', NULL),
('Top Gun: Maverick', 2022, 'Best Picture Candidate', NULL),
('The Fabelmans', 2022, 'Best Picture Candidate', NULL),
('Tár', 2022, 'Best Picture Candidate', NULL),
('Elvis', 2022, 'Best Picture Candidate', NULL),
('Avatar: The Way of Water', 2022, 'Best Picture Candidate', NULL),
('Triangle of Sadness', 2022, 'Best Picture Candidate', NULL),
('Women Talking', 2022, 'Best Picture Candidate', NULL),
('All Quiet on the Western Front', 2022, 'Best Picture Candidate', NULL),
('The Banshees of Inisherin', 2022, 'Best Picture Candidate', NULL),

-- 2023
('Oppenheimer', 2023, 'Best Picture Candidate', NULL),
('Barbie', 2023, 'Best Picture Candidate', NULL),
('Killers of the Flower Moon', 2023, 'Best Picture Candidate', NULL),
('Poor Things', 2023, 'Best Picture Candidate', NULL),
('Past Lives', 2023, 'Best Picture Candidate', NULL),
('The Holdovers', 2023, 'Best Picture Candidate', NULL),
('American Fiction', 2023, 'Best Picture Candidate', NULL),
('Anatomy of a Fall', 2023, 'Best Picture Candidate', NULL),
('Maestro', 2023, 'Best Picture Candidate', NULL),
('The Zone of Interest', 2023, 'Best Picture Candidate', NULL),

-- 2024
('Dune: Part Two', 2024, 'Best Picture Candidate', NULL),
('Anora', 2024, 'Best Picture Candidate', NULL),
('Furiosa: A Mad Max Saga', 2024, 'Best Picture Candidate', NULL),
('Inside Out 2', 2024, 'Best Picture Candidate', NULL),
('Challengers', 2024, 'Best Picture Candidate', NULL),
('Nosferatu', 2024, 'Best Picture Candidate', NULL),
('Gladiator II', 2024, 'Best Picture Candidate', NULL),
('The Brutalist', 2024, 'Best Picture Candidate', NULL),
('Wicked', 2024, 'Best Picture Candidate', NULL),
('Megalopolis', 2024, 'Best Picture Candidate', NULL),

-- 2025
('Project Hail Mary', 2025, 'Best Picture Candidate', NULL),
('Avatar 3', 2025, 'Best Picture Candidate', NULL),
('Mission: Impossible 8', 2025, 'Best Picture Candidate', NULL),
('Superman', 2025, 'Best Picture Candidate', NULL),
('The Batman Part II', 2025, 'Best Picture Candidate', NULL),
('Blade Runner 2099', 2025, 'Best Picture Candidate', NULL),
('Deadpool 3', 2025, 'Best Picture Candidate', NULL),
('Joker: Folie à Deux', 2025, 'Best Picture Candidate', NULL),
('Frozen III', 2025, 'Best Picture Candidate', NULL),
('Fantastic Four', 2025, 'Best Picture Candidate', NULL);