INSERT INTO oscar (titolo, anno, categoria, vincitore) VALUES
('The Godfather', 1972, 'Miglior Film', 'The Godfather'),
('The Godfather', 1972, 'Miglior Attore', 'Marlon Brando'),
('The Godfather', 1972, 'Miglior Sceneggiatura', 'Mario Puzo'),
('Titanic', 1997, 'Miglior Film', 'Titanic'),
('Titanic', 1997, 'Miglior Regia', 'James Cameron'),
('Titanic', 1997, 'Miglior Colonna Sonora', 'James Horner'),
('Gladiator', 2000, 'Miglior Film', 'Gladiator'),
('Gladiator', 2000, 'Miglior Attore', 'Russell Crowe'),
('A Beautiful Mind', 2001, 'Miglior Film', 'A Beautiful Mind'),
('A Beautiful Mind', 2001, 'Miglior Regia', 'Ron Howard'),
('Chicago', 2002, 'Miglior Film', 'Chicago'),
('Chicago', 2002, 'Miglior Attrice Non Protagonista', 'Catherine Zeta-Jones'),
('The Lord of the Rings: The Return of the King', 2003, 'Miglior Film', 'LOTR Return of the King'),
('The Lord of the Rings: The Return of the King', 2003, 'Miglior Regia', 'Peter Jackson'),
('The Lord of the Rings: The Return of the King', 2003, 'Miglior Colonna Sonora', 'Howard Shore'),
('Million Dollar Baby', 2004, 'Miglior Film', 'Million Dollar Baby'),
('Million Dollar Baby', 2004, 'Miglior Regia', 'Clint Eastwood'),
('Million Dollar Baby', 2004, 'Miglior Attrice', 'Hilary Swank'),
('Crash', 2005, 'Miglior Film', 'Crash'),
('Crash', 2005, 'Miglior Sceneggiatura', 'Paul Haggis'),
('The Departed', 2006, 'Miglior Film', 'The Departed'),
('The Departed', 2006, 'Miglior Regia', 'Martin Scorsese'),
('No Country for Old Men', 2007, 'Miglior Film', 'No Country for Old Men'),
('No Country for Old Men', 2007, 'Miglior Attore Non Protagonista', 'Javier Bardem'),
('Slumdog Millionaire', 2008, 'Miglior Film', 'Slumdog Millionaire'),
('Slumdog Millionaire', 2008, 'Miglior Regia', 'Danny Boyle'),
('Slumdog Millionaire', 2008, 'Miglior Colonna Sonora', 'A. R. Rahman'),
('The Hurt Locker', 2009, 'Miglior Film', 'The Hurt Locker'),
('The Hurt Locker', 2009, 'Miglior Regia', 'Kathryn Bigelow'),
('The King’s Speech', 2010, 'Miglior Film', 'The King’s Speech'),
('The King’s Speech', 2010, 'Miglior Attore', 'Colin Firth'),
('The Artist', 2011, 'Miglior Film', 'The Artist'),
('The Artist', 2011, 'Miglior Regia', 'Michel Hazanavicius'),
('Argo', 2012, 'Miglior Film', 'Argo'),
('Argo', 2012, 'Miglior Sceneggiatura', 'Chris Terrio'),
('12 Years a Slave', 2013, 'Miglior Film', '12 Years a Slave'),
('12 Years a Slave', 2013, 'Miglior Attrice Non Protagonista', 'Lupita Nyong’o'),
('Birdman', 2014, 'Miglior Film', 'Birdman'),
('Birdman', 2014, 'Miglior Regia', 'Alejandro G. Iñárritu'),
('Spotlight', 2015, 'Miglior Film', 'Spotlight'),
('Spotlight', 2015, 'Miglior Sceneggiatura', 'Tom McCarthy'),
('Moonlight', 2016, 'Miglior Film', 'Moonlight'),
('Moonlight', 2016, 'Miglior Attore Non Protagonista', 'Mahershala Ali'),
('The Shape of Water', 2017, 'Miglior Film', 'The Shape of Water'),
('The Shape of Water', 2017, 'Miglior Regia', 'Guillermo del Toro'),
('Green Book', 2018, 'Miglior Film', 'Green Book'),
('Green Book', 2018, 'Miglior Attore Non Protagonista', 'Mahershala Ali'),
('Parasite', 2019, 'Miglior Film', 'Parasite'),
('Parasite', 2019, 'Miglior Regia', 'Bong Joon-ho'),
('Nomadland', 2020, 'Miglior Film', 'Nomadland'),
('Nomadland', 2020, 'Miglior Regia', 'Chloé Zhao'),
('CODA', 2021, 'Miglior Film', 'CODA'),
('CODA', 2021, 'Miglior Attore Non Protagonista', 'Troy Kotsur'),
('Everything Everywhere All at Once', 2022, 'Miglior Film', 'Everything Everywhere All at Once'),
('Everything Everywhere All at Once', 2022, 'Miglior Regia', 'Daniels'),
('Everything Everywhere All at Once', 2022, 'Miglior Attrice', 'Michelle Yeoh'),
('Oppenheimer', 2023, 'Miglior Film', 'Oppenheimer'),
('Oppenheimer', 2023, 'Miglior Regia', 'Christopher Nolan'),
('Oppenheimer', 2023, 'Miglior Attore', 'Cillian Murphy'),

-- aggiunte per arrivare a 100
('La La Land', 2016, 'Miglior Colonna Sonora', 'Justin Hurwitz'),
('La La Land', 2016, 'Miglior Attrice', 'Emma Stone'),
('Joker', 2019, 'Miglior Attore', 'Joaquin Phoenix'),
('Joker', 2019, 'Miglior Colonna Sonora', 'Hildur Guðnadóttir'),
('Black Panther', 2018, 'Miglior Costumi', 'Ruth Carter'),
('Black Panther', 2018, 'Miglior Colonna Sonora', 'Ludwig Göransson'),
('Inception', 2010, 'Miglior Fotografia', 'Wally Pfister'),
('Inception', 2010, 'Miglior Effetti Visivi', 'Inception Team'),
('Avatar', 2009, 'Miglior Effetti Visivi', 'Avatar Team'),
('Avatar', 2009, 'Miglior Fotografia', 'Mauro Fiore'),
('Frozen', 2013, 'Miglior Film Animazione', 'Frozen'),
('Frozen', 2013, 'Miglior Canzone', 'Let It Go'),
('Toy Story 3', 2010, 'Miglior Film Animazione', 'Toy Story 3'),
('Toy Story 3', 2010, 'Miglior Canzone', 'We Belong Together'),
('Coco', 2017, 'Miglior Film Animazione', 'Coco'),
('Coco', 2017, 'Miglior Canzone', 'Remember Me'),
('Up', 2009, 'Miglior Film Animazione', 'Up'),
('Up', 2009, 'Miglior Colonna Sonora', 'Michael Giacchino'),
('Brave', 2012, 'Miglior Film Animazione', 'Brave'),
('Soul', 2020, 'Miglior Film Animazione', 'Soul'),
('Soul', 2020, 'Miglior Colonna Sonora', 'Trent Reznor'),
('The Dark Knight', 2008, 'Miglior Attore Non Protagonista', 'Heath Ledger'),
('The Dark Knight', 2008, 'Miglior Montaggio Sonoro', 'Richard King'),
('Mad Max: Fury Road', 2015, 'Miglior Montaggio', 'Margaret Sixel'),
('Mad Max: Fury Road', 2015, 'Miglior Costumi', 'Jenny Beavan'),
('Dune', 2021, 'Miglior Fotografia', 'Greig Fraser'),
('Dune', 2021, 'Miglior Colonna Sonora', 'Hans Zimmer'),
('Dune', 2021, 'Miglior Effetti Visivi', 'Dune Team'),
('Interstellar', 2014, 'Miglior Effetti Visivi', 'Interstellar Team'),
('Gravity', 2013, 'Miglior Regia', 'Alfonso Cuarón'),
('Gravity', 2013, 'Miglior Fotografia', 'Emmanuel Lubezki'),
('The Revenant', 2015, 'Miglior Attore', 'Leonardo DiCaprio'),
('The Revenant', 2015, 'Miglior Regia', 'Alejandro G. Iñárritu'),
('Bohemian Rhapsody', 2018, 'Miglior Attore', 'Rami Malek'),
('Bohemian Rhapsody', 2018, 'Miglior Montaggio', 'John Ottman'),
('Ford v Ferrari', 2019, 'Miglior Montaggio', 'Michael McCusker'),
('Ford v Ferrari', 2019, 'Miglior Montaggio Sonoro', 'Donald Sylvester'),
('The Social Network', 2010, 'Miglior Sceneggiatura', 'Aaron Sorkin'),
('The Social Network', 2010, 'Miglior Montaggio', 'Kirk Baxter');
